name = "localregistry2"
uuid = "1fc9fc9f-0e3b-4b6d-a690-7629fe104a0e"
repo = "https://github.com/Dale-Muccignat/localregistry2"
description = "My private registry"

[packages]
14d21136-4a01-4484-96ec-002222588dc1 = { name = "Master", path = "M/Master" }
2c68f703-1361-4b11-b625-5488bb42ec3f = { name = "Gases", path = "G/Gases" }
a0cff5f7-4399-4d78-90d8-99a93a19fb99 = { name = "RSequences", path = "R/RSequences" }
a7da4855-385b-4a38-b0bb-3181bd9fb17a = { name = "MCLuJ", path = "M/MCLuJ" }
cf7a8319-7422-45e1-9d9d-09d2f3292ef7 = { name = "AndersonAcceleration", path = "A/AndersonAcceleration" }
